TapAPITradeLoginAuth = {
    "UserNo": "string",
    "AuthCode": "string",
    "AppID": "string",
    "ISModifyPassword": "char",
    "Password": "string",
    "NewPassword": "string",
    "ISDDA": "char",
    "DDASerialNo": "string",
    "NoticeIgnoreFlag": "unsigned int",
}

TapAPITradeLoginRspInfo = {
    "UserNo": "string",
    "UserType": "int",
    "UserName": "string",
    "QuoteTempPassword": "string",
    "ReservedInfo": "string",
    "LastLoginIP": "string",
    "LastLoginPort": "unsigned int",
    "LastLoginInfo": "string",
    "LastLoginTime": "string",
    "LastLogoutTime": "string",
    "TradeDate": "string",
    "LastSettleTime": "string",
    "StartTime": "string",
    "InitTime": "string",
    "AuthType": "char",
    "AuthDate": "string",
    "UdpCertCode": "unsigned long long",
}

TapAPISubmitUserLoginInfo = {
    "UserNo": "string",
    "GatherInfo": "string",
    "ClientLoginIP": "string",
    "ClientLoginPort": "unsigned int",
    "ClientLoginDateTime": "string",
    "ClientAppID": "string",
    "AuthKeyVersion": "unsigned int",
}

TapAPISubmitUserLoginRspInfo = {
    "UserNo": "string",
    "ErrorCode": "unsigned int",
    "ErrorText": "string",
}

TapAPIAccQryReq = {
    "AccountNo": "string",
}

TapAPIAccountInfo = {
    "AccountNo": "string",
    "AccountType": "char",
    "AccountState": "char",
    "AccountShortName": "string",
    "AccountIsDocHolder": "char",
    "IsMarketMaker": "char",
    "AccountFamilyType": "char",
}

TapAPINewOrder = {
    "AccountNo": "string",
    "ExchangeNo": "string",
    "CommodityType": "char",
    "CommodityNo": "string",
    "ContractNo": "string",
    "StrikePrice": "string",
    "CallOrPutFlag": "char",
    "ContractNo2": "string",
    "StrikePrice2": "string",
    "CallOrPutFlag2": "char",
    "OrderType": "char",
    "OrderSource": "char",
    "TimeInForce": "char",
    "ExpireTime": "string",
    "IsRiskOrder": "char",
    "OrderSide": "char",
    "PositionEffect": "char",
    "PositionEffect2": "char",
    "InquiryNo": "string",
    "HedgeFlag": "char",
    "OrderPrice": "double",
    "OrderPrice2": "double",
    "StopPrice": "double",
    "OrderQty": "unsigned int",
    "OrderMinQty": "unsigned int",
    "MinClipSize": "unsigned int",
    "MaxClipSize": "unsigned int",
    "RefInt": "int",
    "RefString": "string",
    "TacticsType": "char",
    "TriggerCondition": "char",
    "TriggerPriceType": "char",
    "AddOneIsValid": "char",
    "OrderQty2": "unsigned int",
    "HedgeFlag2": "char",
    "MarketLevel": "unsigned char",
    "FutureAutoCloseFlag": "char",
    "UpperChannelNo": "string",
}

TapAPICommodityOrderTypeQryRsp = {
    "Commodity": "TapAPICommodity",
    "Count": "int",
    "OrderTypes": "TAPIOrderTypeType*",
}

TapAPICommodityOrderTimeInForceQryRsp = {
    "Commodity": "TapAPICommodity",
    "Count": "int",
    "OrderTimeInForces": "TAPITimeInForceType*",
}

TapAPIOrderInfo = {
    "AccountNo": "string",
    "ExchangeNo": "string",
    "CommodityType": "char",
    "CommodityNo": "string",
    "ContractNo": "string",
    "StrikePrice": "string",
    "CallOrPutFlag": "char",
    "ContractNo2": "string",
    "StrikePrice2": "string",
    "CallOrPutFlag2": "char",
    "OrderType": "char",
    "OrderSource": "char",
    "TimeInForce": "char",
    "ExpireTime": "string",
    "IsRiskOrder": "char",
    "OrderSide": "char",
    "PositionEffect": "char",
    "PositionEffect2": "char",
    "InquiryNo": "string",
    "HedgeFlag": "char",
    "OrderPrice": "double",
    "OrderPrice2": "double",
    "StopPrice": "double",
    "OrderQty": "unsigned int",
    "OrderMinQty": "unsigned int",
    "OrderCanceledQty": "unsigned int",
    "MinClipSize": "unsigned int",
    "MaxClipSize": "unsigned int",
    "LicenseNo": "string",
    "RefInt": "int",
    "RefString": "string",
    "ParentAccountNo": "string",
    "ServerFlag": "char",
    "OrderNo": "string",
    "ClientOrderNo": "string",
    "OrderLocalNo": "string",
    "OrderSystemNo": "string",
    "OrderExchangeSystemNo": "string",
    "OrderParentNo": "string",
    "OrderParentSystemNo": "string",
    "TradeNo": "string",
    "UpperNo": "string",
    "UpperChannelNo": "string",
    "UpperSettleNo": "string",
    "UpperUserNo": "string",
    "OrderInsertUserNo": "string",
    "OrderInsertTime": "string",
    "OrderCommandUserNo": "string",
    "OrderUpdateUserNo": "string",
    "OrderUpdateTime": "string",
    "OrderState": "char",
    "OrderMatchPrice": "double",
    "OrderMatchPrice2": "double",
    "OrderMatchQty": "unsigned int",
    "OrderMatchQty2": "unsigned int",
    "ErrorCode": "unsigned int",
    "ErrorText": "string",
    "IsBackInput": "char",
    "IsDeleted": "char",
    "IsAddOne": "char",
    "OrderStreamID": "unsigned int",
    "UpperStreamID": "unsigned int",
    "ContractSize": "double",
    "ContractSize2": "double",
    "CommodityCurrencyGroup": "string",
    "CommodityCurrency": "string",
    "FeeMode": "char",
    "FeeParam": "double",
    "FeeCurrencyGroup": "string",
    "FeeCurrency": "string",
    "FeeMode2": "char",
    "FeeParam2": "double",
    "FeeCurrencyGroup2": "string",
    "FeeCurrency2": "string",
    "MarginMode": "char",
    "MarginParam": "double",
    "MarginMode2": "char",
    "MarginParam2": "double",
    "PreSettlePrice": "double",
    "PreSettlePrice2": "double",
    "OpenVol": "unsigned int",
    "CoverVol": "unsigned int",
    "OpenVol2": "unsigned int",
    "CoverVol2": "unsigned int",
    "FeeValue": "double",
    "MarginValue": "double",
    "TacticsType": "char",
    "TriggerCondition": "char",
    "TriggerPriceType": "char",
    "AddOneIsValid": "char",
    "OrderQty2": "unsigned int",
    "HedgeFlag2": "char",
    "MarketLevel": "unsigned char",
    "OrderDeleteByDisConnFlag": "char",
}

TapAPIOrderInfoNotice = {
    "SessionID": "unsigned int",
    "ErrorCode": "unsigned int",
    "OrderInfo": "TapAPIOrderInfo*",
}

TapAPIOrderActionRsp = {
    "ActionType": "char",
    "OrderInfo": "TapAPIOrderInfo*",
}

TapAPIAmendOrder = {
    "ReqData": "TapAPINewOrder",
    "ServerFlag": "char",
    "OrderNo": "string",
}

TapAPIOrderCancelReq = {
    "RefInt": "int",
    "RefString": "string",
    "ServerFlag": "char",
    "OrderNo": "string",
}

TapAPIOrderQryReq = {
    "OrderQryType": "char",
}

TapAPIOrderProcessQryReq = {
    "ServerFlag": "char",
    "OrderNo": "string",
}

TapAPIFillQryReq = {
    "StreamID": "unsigned int",
}

TapAPIFillInfo = {
    "AccountNo": "string",
    "ParentAccountNo": "string",
    "ExchangeNo": "string",
    "CommodityType": "char",
    "CommodityNo": "string",
    "ContractNo": "string",
    "StrikePrice": "string",
    "CallOrPutFlag": "char",
    "ExchangeNoRef": "string",
    "CommodityTypeRef": "char",
    "CommodityNoRef": "string",
    "ContractNoRef": "string",
    "StrikePriceRef": "string",
    "CallOrPutFlagRef": "char",
    "OrderExchangeNo": "string",
    "OrderCommodityType": "char",
    "OrderCommodityNo": "string",
    "OrderType": "char",
    "MatchSource": "char",
    "TimeInForce": "char",
    "ExpireTime": "string",
    "IsRiskOrder": "char",
    "MatchSide": "char",
    "PositionEffect": "char",
    "PositionEffectRef": "char",
    "HedgeFlag": "char",
    "ServerFlag": "char",
    "OrderNo": "string",
    "OrderLocalNo": "string",
    "MatchNo": "string",
    "ExchangeMatchNo": "string",
    "MatchDateTime": "string",
    "UpperMatchDateTime": "string",
    "UpperNo": "string",
    "UpperChannelNo": "string",
    "UpperSettleNo": "string",
    "UpperUserNo": "string",
    "TradeNo": "string",
    "MatchPrice": "double",
    "MatchQty": "unsigned int",
    "IsBackInput": "char",
    "IsDeleted": "char",
    "IsAddOne": "char",
    "MatchStreamID": "unsigned int",
    "UpperStreamID": "unsigned int",
    "OpenCloseMode": "char",
    "ContractSize": "double",
    "CommodityCurrencyGroup": "string",
    "CommodityCurrency": "string",
    "FeeMode": "char",
    "FeeParam": "double",
    "FeeCurrencyGroup": "string",
    "FeeCurrency": "string",
    "PreSettlePrice": "double",
    "FeeValue": "double",
    "IsManualFee": "char",
    "Turnover": "double",
    "PremiumIncome": "double",
    "PremiumPay": "double",
    "OppoMatchNo": "string",
    "CloseProfit": "double",
    "UnExpProfit": "double",
    "UpperMatchPrice": "double",
    "QuotePrice": "double",
    "ClosePL": "double",
}

TapAPICloseQryReq = {
}

TapAPIPositionQryReq = {
}

TapAPIPositionInfo = {
    "AccountNo": "string",
    "ParentAccountNo": "string",
    "ExchangeNo": "string",
    "CommodityType": "char",
    "CommodityNo": "string",
    "ContractNo": "string",
    "StrikePrice": "string",
    "CallOrPutFlag": "char",
    "ExchangeNoRef": "string",
    "CommodityTypeRef": "char",
    "CommodityNoRef": "string",
    "ContractNoRef": "string",
    "StrikePriceRef": "string",
    "CallOrPutFlagRef": "char",
    "OrderExchangeNo": "string",
    "OrderCommodityType": "char",
    "OrderCommodityNo": "string",
    "OrderType": "char",
    "MatchSource": "char",
    "TimeInForce": "char",
    "ExpireTime": "string",
    "MatchSide": "char",
    "HedgeFlag": "char",
    "PositionNo": "string",
    "ServerFlag": "char",
    "OrderNo": "string",
    "MatchNo": "string",
    "ExchangeMatchNo": "string",
    "MatchDate": "string",
    "MatchTime": "string",
    "UpperMatchTime": "string",
    "UpperNo": "string",
    "UpperSettleNo": "string",
    "UpperUserNo": "string",
    "TradeNo": "string",
    "PositionPrice": "double",
    "PositionQty": "unsigned int",
    "IsBackInput": "char",
    "IsAddOne": "char",
    "MatchStreamID": "unsigned int",
    "PositionStreamId": "unsigned int",
    "OpenCloseMode": "char",
    "ContractSize": "double",
    "CommodityCurrencyGroup": "string",
    "CommodityCurrency": "string",
    "PreSettlePrice": "double",
    "SettlePrice": "double",
    "Turnover": "double",
    "AccountMarginMode": "char",
    "AccountMarginParam": "double",
    "UpperMarginMode": "char",
    "UpperMarginParam": "double",
    "AccountInitialMargin": "double",
    "AccountMaintenanceMargin": "double",
    "UpperInitialMargin": "double",
    "UpperMaintenanceMargin": "double",
    "PositionProfit": "double",
    "LMEPositionProfit": "double",
    "OptionMarketValue": "double",
    "MatchCmbNo": "string",
    "IsHistory": "char",
    "FloatingPL": "double",
}

TapAPIPositionProfit = {
    "PositionNo": "string",
    "PositionStreamId": "unsigned int",
    "PositionProfit": "double",
    "LMEPositionProfit": "double",
    "OptionMarketValue": "double",
    "CalculatePrice": "double",
    "FloatingPL": "double",
}

TapAPIPositionProfitNotice = {
    "IsLast": "char",
    "Data": "TapAPIPositionProfit*",
}

TapAPICloseInfo = {
    "AccountNo": "string",
    "ParentAccountNo": "string",
    "ExchangeNo": "string",
    "CommodityType": "char",
    "CommodityNo": "string",
    "ContractNo": "string",
    "StrikePrice": "string",
    "CallOrPutFlag": "char",
    "OpenOrderExchangeNo": "string",
    "OpenOrderCommodityType": "char",
    "OpenOrderCommodityNo": "string",
    "CloseOrderExchangeNo": "string",
    "CloseOrderCommodityType": "char",
    "CloseOrderCommodityNo": "string",
    "OpenMatchSource": "char",
    "CloseMatchSource": "char",
    "CloseSide": "char",
    "CloseQty": "unsigned int",
    "OpenPrice": "double",
    "ClosePrice": "double",
    "OpenServerFlag": "char",
    "OpenOrderNo": "string",
    "OpenMatchNo": "string",
    "OpenExchangeMatchNo": "string",
    "OpenMatchDateTime": "string",
    "CloseServerFlag": "char",
    "CloseOrderNo": "string",
    "CloseMatchNo": "string",
    "CloseExchangeMatchNo": "string",
    "CloseMatchDateTime": "string",
    "CloseStreamId": "unsigned int",
    "OpenCloseMode": "char",
    "ContractSize": "double",
    "CommodityCurrencyGroup": "string",
    "CommodityCurrency": "string",
    "PreSettlePrice": "double",
    "PremiumIncome": "double",
    "PremiumPay": "double",
    "CloseProfit": "double",
    "UnExpProfit": "double",
    "ClosePL": "double",
}

TapAPIFundReq = {
    "AccountNo": "string",
}

TapAPIFundData = {
    "AccountNo": "string",
    "ParentAccountNo": "string",
    "CurrencyGroupNo": "string",
    "CurrencyNo": "string",
    "TradeRate": "double",
    "FutureAlg": "char",
    "OptionAlg": "char",
    "PreBalance": "double",
    "PreUnExpProfit": "double",
    "PreLMEPositionProfit": "double",
    "PreEquity": "double",
    "PreAvailable1": "double",
    "PreMarketEquity": "double",
    "CashInValue": "double",
    "CashOutValue": "double",
    "CashAdjustValue": "double",
    "CashPledged": "double",
    "FrozenFee": "double",
    "FrozenDeposit": "double",
    "AccountFee": "double",
    "ExchangeFee": "double",
    "AccountDeliveryFee": "double",
    "PremiumIncome": "double",
    "PremiumPay": "double",
    "CloseProfit": "double",
    "DeliveryProfit": "double",
    "UnExpProfit": "double",
    "ExpProfit": "double",
    "PositionProfit": "double",
    "LmePositionProfit": "double",
    "OptionMarketValue": "double",
    "AccountIntialMargin": "double",
    "AccountMaintenanceMargin": "double",
    "UpperInitalMargin": "double",
    "UpperMaintenanceMargin": "double",
    "Discount": "double",
    "Balance": "double",
    "Equity": "double",
    "Available": "double",
    "CanDraw": "double",
    "MarketEquity": "double",
    "OriginalCashInOut": "double",
    "FloatingPL": "double",
    "FrozenRiskFundValue": "double",
    "ClosePL": "double",
    "NoCurrencyPledgeValue": "double",
    "PrePledgeValue": "double",
    "PledgeIn": "double",
    "PledgeOut": "double",
    "PledgeValue": "double",
    "BorrowValue": "double",
    "SpecialAccountFrozenMargin": "double",
    "SpecialAccountMargin": "double",
    "SpecialAccountFrozenFee": "double",
    "SpecialAccountFee": "double",
    "SpecialFloatProfit": "double",
    "SpecialCloseProfit": "double",
    "SpecialFloatPL": "double",
    "SpecialClosePL": "double",
}

TapAPICommodityInfo = {
    "ExchangeNo": "string",
    "CommodityType": "char",
    "CommodityNo": "string",
    "CommodityName": "string",
    "CommodityEngName": "string",
    "RelateExchangeNo": "string",
    "RelateCommodityType": "char",
    "RelateCommodityNo": "string",
    "RelateExchangeNo2": "string",
    "RelateCommodityType2": "char",
    "RelateCommodityNo2": "string",
    "TradeCurrency": "string",
    "SettleCurrency": "string",
    "ContractSize": "double",
    "MarginCalculateMode": "char",
    "OptionMarginCalculateMode": "char",
    "OpenCloseMode": "char",
    "StrikePriceTimes": "double",
    "IsOnlyQuoteCommodity": "char",
    "CommodityTickSize": "double",
    "CommodityDenominator": "int",
    "CmbDirect": "char",
    "OnlyCanCloseDays": "int",
    "DeliveryMode": "char",
    "DeliveryDays": "int",
    "AddOneTime": "string",
    "CommodityTimeZone": "int",
}

TapAPITradeContractInfo = {
    "ExchangeNo": "string",
    "CommodityType": "char",
    "CommodityNo": "string",
    "ContractNo1": "string",
    "StrikePrice1": "string",
    "CallOrPutFlag1": "char",
    "ContractNo2": "string",
    "StrikePrice2": "string",
    "CallOrPutFlag2": "char",
    "ContractType": "char",
    "QuoteUnderlyingContract": "string",
    "ContractName": "string",
    "ContractExpDate": "string",
    "LastTradeDate": "string",
    "FirstNoticeDate": "string",
    "FutureContractNo": "string",
}

TapAPIDeepQuoteInfo = {
    "Side": "char",
    "Price": "double",
    "Qty": "unsigned int",
}

TapAPIDeepQuoteQryRsp = {
    "Contract": "TapAPIContract",
    "DeepQuote": "TapAPIDeepQuoteInfo",
}

TapAPIExchangeStateInfoQryReq = {
}

TapAPIExchangeStateInfo = {
    "UpperChannelNo": "string",
    "ExchangeNo": "string",
    "CommodityType": "char",
    "CommodityNo": "string",
    "ExchangeTime": "string",
    "TradingState": "char",
}

TapAPIExchangeStateInfoNotice = {
    "IsLast": "char",
    "ExchangeStateInfo": "TapAPIExchangeStateInfo",
}

TapAPIReqQuoteNotice = {
    "ExchangeNo": "string",
    "CommodityType": "char",
    "CommodityNo": "string",
    "ContractNo": "string",
    "StrikePrice": "string",
    "CallOrPutFlag": "char",
    "InquiryNo": "string",
    "UpdateTime": "string",
}

TapAPIUpperChannelQryReq = {
}

TapAPIUpperChannelInfo = {
    "UpperChannelNo": "string",
    "UpperChannelName": "string",
    "UpperNo": "string",
    "UpperUserNo": "string",
}

TapAPIAccountRentQryReq = {
    "AccountNo": "string",
    "ExchangeNo": "string",
    "CommodityType": "char",
    "CommodityNo": "string",
    "ContractNo": "string",
}

TapAPIAccountRentInfo = {
    "AccountNo": "string",
    "ExchangeNo": "string",
    "CommodityType": "char",
    "CommodityNo": "string",
    "ContractNo": "string",
    "MatchSource": "char",
    "CurrencyNo": "string",
    "FeeMode": "char",
    "OpenTurnover": "double",
    "ClosedTurnover": "double",
    "CloseNewTurnover": "double",
    "OpenVolume": "double",
    "ClosedVolume": "double",
    "CloseNewVolume": "double",
    "MarginMode": "char",
    "BuyTInitMargin": "double",
    "SellTInitMargin": "double",
    "BuyBInitMargin": "double",
    "SellBInitMargin": "double",
    "BuyLInitMargin": "double",
    "SellLInitMargin": "double",
    "BuyMInitMargin": "double",
    "SellMInitMargin": "double",
    "BuyTMaintMargin": "double",
    "SellTMaintMargin": "double",
    "BuyBMaintMargin": "double",
    "SellBMaintMargin": "double",
    "BuyLMaintMargin": "double",
    "SellLMaintMargin": "double",
    "BuyMMaintMargin": "double",
    "SellMMaintMargin": "double",
}

TapAPIBillQryReq = {
    "UserNo": "string",
    "BillType": "char",
    "BillDate": "string",
    "BillFileType": "char",
}

TapAPIBillQryRsp = {
    "Reqdata": "dict",
    "BillLen": "int",
    "BillText": "char",
}

TapAPIAccountStorageQryReq = {
    "AccountNo": "string",
}

TapAPIAccountStorageInfo = {
    "AccountNo": "string",
    "ExchangeNo": "string",
    "CommodityType": "char",
    "CommodityNo": "string",
    "StorageQty": "double",
}

